from: "lsfb500_r50_base.yaml"

datasets:
  training:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+non-norm-img"

  validation:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+non-norm-img"

  testing:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+non-norm-img"

experiment:
  suffix: "lsfb/lsfb500/no-minmax-with-norm"
