from: "lsfb500_r50_base.yaml"

datasets:
  training:
    preprocessing:
      pose_transform_pipeline: "concat+resample-nearest+rgb-img"

  validation:
    preprocessing:
      pose_transform_pipeline: "concat+resample-nearest+rgb-img"

  testing:
    preprocessing:
      pose_transform_pipeline: "concat+resample-nearest+rgb-img"

experiment:
  suffix: "lsfb500/no-linear-interp"
