datasets:
  training:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_{000000..000003}.tar"
    loader:
      batch_size: 32
      shuffle: true
      flatten_pose: true
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+rgb-img"
#      pose_transform_pipeline: "concat+resample-nearest+rgb-img"
      input_type: 'rgb'

  validation:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_000004.tar"
    loader:
      batch_size: 32
      shuffle: False
      flatten_pose: true
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+rgb-img"
      input_type: 'rgb'

  testing:
    shards_url: "file:E:/datasets/sign-language/lsfb-isol/shards/500/shard_000004.tar"
    loader:
      batch_size: 32
      shuffle: false
      flatten_pose: true
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+rgb-img"
      input_type: 'rgb'

model:
  type: 'multi-head'
  backbone:
    type: 'vit'
    args:
      c_out: 500
      dropout: 0.1
  heads:
    classification:
      type: 'identity'
      in_channels: 500
      out_channels: 500

training:
  criterion:
    classification:
      name: "cross-entropy"
      use_weights: false
  max_epochs: 500
  early_stopping_patience: 30
  learning_rate: 1e-3
  is_output_multilayer: false
  n_classes: 500
  overfit_one_batch: false

experiment:
  id: "islr"
  suffix: "lsfb/lsfb500/debug"
  seed: 'random'
  output_dir: "D:/data/sign-languages/outs/slp2/isolated-recognition"
#  mlflow_uri: "http://127.0.0.1:8142"
  show_progress_bar: true
  debug: false
