from: "lsfb500_r50_base.yaml"

datasets:
  training:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+rgb-img"

  validation:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+rgb-img"

  testing:
    preprocessing:
      pose_transform_pipeline: "concat+resample-linear+norm+rgb-img"

experiment:
  suffix: "lsfb/lsfb500/norm"
